"use client";

// import type { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import "./globals.css";
import React, { useEffect } from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { App, Button, ConfigProvider, Layout, notification, Space } from "antd";
import { HeaderMenu } from "@/components/HeaderMenu";
import { SiteFooter } from "@/components/SiteFooter";
import { THEME_CONFIG } from "@/shared/constants/theme";
import { ApiProvider } from "@reduxjs/toolkit/query/react";
import { Api } from "@/services/api";
import dayjs from "dayjs";
import { YandexMetricaProvider } from "next-yandex-metrica";
import locale from "antd/locale/ru_RU";
import { CookiesProvider, useCookies } from "react-cookie";
import { Notification } from "@/components/CookiesNotification";
import Favicon from "@/components/Favicon";

require("dayjs/locale/ru");
dayjs.locale("ru");

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [api, contextHolder] = notification.useNotification();
    const [cookies, setCookie] = useCookies(["cuply_policy"]);

    const isDev = process.env.NEXT_PUBLIC_APP_URL === "https://stage.cuply.pro";

    const openNotification = () => {
        const btn = (
            <Space>
                <Button
                    type="primary"
                    onClick={() => {
                        setCookie("cuply_policy", true);
                        api.destroy("cookie-policy");
                    }}
                >
                    OK
                </Button>
            </Space>
        );

        api.open({
            message: "Используем куки и рекомендательные технологии",
            description: <Notification />,
            btn,
            duration: null,
            key: "cookie-policy",
            placement: "bottomRight",
            closeIcon: false,
            className: "cookie-policy",
        });
    };

    useEffect(() => {
        if (!cookies.cuply_policy) {
            openNotification();
        }
    }, [cookies.cuply_policy]);

    return (
        <html lang="en">
            <head>
                <Favicon />
                <title>{`${isDev ? "⚙️ " : ""}CUPLY - Турниры`}</title>
            </head>
            <body>
                <YandexMetricaProvider
                    tagID={isDev ? undefined : 97871523}
                    initParameters={{
                        clickmap: true,
                        trackLinks: true,
                        accurateTrackBounce: true,
                        webvisor: true,
                    }}
                >
                    <CookiesProvider defaultSetOptions={{ path: "/" }}>
                        <ApiProvider api={Api}>
                            <AntdRegistry>
                                <ConfigProvider
                                    theme={THEME_CONFIG}
                                    locale={locale}
                                >
                                    <App>
                                        <Layout>
                                            <HeaderMenu />
                                            <Layout
                                                style={{
                                                    minHeight:
                                                        "calc(100vh - var(--cuply-header-height))",
                                                    marginTop: 64,
                                                    background:
                                                        "var(--cuply-main-bg)",
                                                    display: "flex",
                                                    flexDirection: "column",
                                                }}
                                            >
                                                <div style={{ flex: 1 }}>
                                                    {children}
                                                </div>
                                                <SiteFooter />
                                            </Layout>
                                        </Layout>
                                    </App>
                                    {contextHolder}
                                </ConfigProvider>
                            </AntdRegistry>
                        </ApiProvider>
                    </CookiesProvider>
                </YandexMetricaProvider>
            </body>
        </html>
    );
}
