const countries = [
    "Таджикистан",
    "Белоруссия",
    "Турция",
    "Казахстан",
    "Бразилия",
    "Россия",
    "ОАЭ",
    "Бельгия",
];

var nameList = [
    "Time",
    "Past",
    "Future",
    "Dev",
    "Fly",
    "Flying",
    "Soar",
    "Soaring",
    "Power",
    "Falling",
    "Fall",
    "Jump",
    "Cliff",
    "Mountain",
    "Rend",
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Gold",
    "Demon",
    "Demonic",
    "Panda",
    "Cat",
    "Kitty",
    "Kitten",
    "Zero",
    "Memory",
    "Trooper",
    "XX",
    "Bandit",
    "Fear",
    "Light",
    "Glow",
    "Tread",
    "Deep",
    "Deeper",
    "Deepest",
    "Mine",
    "Your",
    "Worst",
    "Enemy",
    "Hostile",
    "Force",
    "Video",
    "Game",
    "Donkey",
    "Mule",
    "Colt",
    "Cult",
    "Cultist",
    "Magnum",
    "Gun",
    "Assault",
    "Recon",
    "Trap",
    "Trapper",
    "Redeem",
    "Code",
    "Script",
    "Writer",
    "Near",
    "Close",
    "Open",
    "Cube",
    "Circle",
    "Geo",
    "Genome",
    "Germ",
    "Spaz",
    "Shot",
    "Echo",
    "Beta",
    "Alpha",
    "Gamma",
    "Omega",
    "Seal",
    "Squid",
    "Money",
    "Cash",
    "Lord",
    "King",
    "Duke",
    "Rest",
    "Fire",
    "Flame",
    "Morrow",
    "Break",
    "Breaker",
    "Numb",
    "Ice",
    "Cold",
    "Rotten",
    "Sick",
    "Sickly",
    "Janitor",
    "Camel",
    "Rooster",
    "Sand",
    "Desert",
    "Dessert",
    "Hurdle",
    "Racer",
    "Eraser",
    "Erase",
    "Big",
    "Small",
    "Short",
    "Tall",
    "Sith",
    "Bounty",
    "Hunter",
    "Cracked",
    "Broken",
    "Sad",
    "Happy",
    "Joy",
    "Joyful",
    "Crimson",
    "Destiny",
    "Deceit",
    "Lies",
    "Lie",
    "Honest",
    "Destined",
    "Bloxxer",
    "Hawk",
    "Eagle",
    "Hawker",
    "Walker",
    "Zombie",
    "Sarge",
    "Capt",
    "Captain",
    "Punch",
    "One",
    "Two",
    "Uno",
    "Slice",
    "Slash",
    "Melt",
    "Melted",
    "Melting",
    "Fell",
    "Wolf",
    "Hound",
    "Legacy",
    "Sharp",
    "Dead",
    "Mew",
    "Chuckle",
    "Bubba",
    "Bubble",
    "Sandwich",
    "Smasher",
    "Extreme",
    "Multi",
    "Universe",
    "Ultimate",
    "Death",
    "Ready",
    "Monkey",
    "Elevator",
    "Wrench",
    "Grease",
    "Head",
    "Theme",
    "Grand",
    "Cool",
    "Kid",
    "Boy",
    "Girl",
    "Vortex",
    "Paradox",
];

const getParticipant = () => ({
    id: Math.random(),
    tournament: {
        id: 7,
        name: "ЛЕТНИЙ КВ FC24",
    },
    account: {
        id: Math.random(),
        game: {
            id: 1,
            name: "EA FC24",
        },
        platform: {
            id: 1,
            name: "PS5",
        },
        login: nameList[Math.floor(Math.random() * nameList.length)],
        user: {
            id: Math.random(),
            name: "Иван",
            surname: "Иванов",
            email: "mail@mail.ru",
            username: "OnlinePon4ik",
            country: countries[Math.floor(Math.random() * 7)],
            city: "Москва",
        },
        created_at: "2024-07-19T18:01:45.183804Z",
        updated_at: "2024-07-19T18:01:45.184022Z",
    },
    status: 3,
    created_at: "2024-07-19T18:01:44.978712Z",
    updated_at: "2024-07-20T07:31:08.153594Z",
});

const getPair = () => ({
    id: Math.random(),
    tournament_id: 7,
    short_id: 7,
    branch_type: 2,
    state: 1,
    is_bye: false,
    is_initial: true,
    round: 1,
    next_winner_id: "",
    next_loser_id: "",
    gamers_assigned_at: "",
    is_team_shown: false,
    gamer1: getParticipant(),
    gamer2: getParticipant(),
    created_at: "2024-07-19T18:01:45.183804Z",
    updated_at: "2024-07-19T18:01:45.184022Z",
});

const teams = [
    {
        img: "20-d42772a0-f5d9-4b30-a4ba-1f4ab8af276f",
        name: "bl_bayern",
        title: "Bundesliga: Bayern Munich",
    },
    {
        img: "20-6a9f3448-f770-49bd-9b76-2eddf397acf8",
        name: "bl_borussia",
        title: "Bundesliga: Borussia",
    },
    {
        img: "20-2a13881a-503d-4e7c-b506-644abd4095c8",
        name: "bl_levrkusen",
        title: "Bundesliga: Levrkusen",
    },
    {
        img: "20-c781e25a-d96a-4b29-b0b2-808f0759514a",
        name: "epl_arsenal",
        title: "English Premier League:: Arsenal",
    },
    // "epl_chelsea",
    // "epl_liverpool",
    // "epl_manchester_city",
    // "epl_manchester_united",
    // "epl_tottenham",
    // "fan_africa",
    // "fan_concacaf",
    // "fan_heroes",
    // "fan_scandinavia",
    // "fan_south_america",
    // "fan_ussr",
    // "fan_yugoslavia",
    // "l1_psg",
    // "lea_bundesliga",
    // "lea_dutch_league",
    // "lea_la_liga",
    // "lea_ligue",
    // "lea_mls_league",
    // "lea_portugal",
    // "lea_premier_league",
    // "lea_saudi_league",
    // "lea_serie_a",
    // "lea_turkish_league",
    // "ll_atletico_madrid",
    // "ll_barcelona",
    // "ll_real_madrid",
    // "nat_argentina",
    // "nat_belgium",
    // "nat_brasil",
    // "nat_colombia",
    // "nat_england",
    // "nat_france",
    // "nat_germany",
    // "nat _italy",
    // "nat_netherlands",
    // "nat_portugal",
    // "nat_spain",
    // "nat_uruguay",
    // "nat_usa",
    // "sa_Inter_milano",
    // "sa_juventus",
    // "sa_milan",
    // "sa_roma",
];
export const getTeams = () => ({
    id: Math.random(),
    img: teams[Math.floor(Math.random() * 3)].img,
    title: "Title",
});

export const participantsMock = Array<ReturnType<typeof getParticipant>>(150)
    .fill(getParticipant())
    .map(getParticipant);

export const pairsMock = Array<
    [ReturnType<typeof getParticipant>, ReturnType<typeof getParticipant>]
>(50)
    .fill([getParticipant(), getParticipant()])
    .map(() => [getParticipant(), getParticipant()]);
