"""add_creator_to_tournaments

Revision ID: 0004
Revises: 0003
Create Date: 2024-07-03 04:48:16.616080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.add_column('tournaments', sa.Column('description', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'tournaments', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'description')
    op.drop_column('tournaments', 'creator_id')
    # ### end Alembic commands ###
