"""extend_user

Revision ID: 0005
Revises: 0004
Create Date: 2024-07-07 00:27:00.040877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('rating', sa.Integer(), nullable=True))
    op.drop_column('users', 'patronymic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patronymic', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'rating')
    op.drop_column('users', 'city')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
