"""extend_obligatory_columns_in_user

Revision ID: 0006
Revises: 0005
Create Date: 2024-07-07 00:31:32.040653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'country',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'city',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'city',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'country',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
