"""add_game_and_platforms

Revision ID: 0008
Revises: 0007
Create Date: 2024-07-10 01:59:55.323436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gamers', sa.Column('game_id', sa.Integer(), nullable=False))
    op.add_column('gamers', sa.Column('platform_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'gamers', 'platforms', ['platform_id'], ['id'])
    op.create_foreign_key(None, 'gamers', 'games', ['game_id'], ['id'])
    op.drop_column('gamers', 'games')
    op.drop_column('gamers', 'platforms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamers', sa.Column('platforms', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('gamers', sa.Column('games', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gamers', type_='foreignkey')
    op.drop_constraint(None, 'gamers', type_='foreignkey')
    op.drop_column('gamers', 'platform_id')
    op.drop_column('gamers', 'game_id')
    op.drop_table('platforms')
    op.drop_table('games')
    # ### end Alembic commands ###
