"""extend_tournaments

Revision ID: 0009
Revises: 0008
Create Date: 2024-07-11 01:00:24.282592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('game_id', sa.Integer(), nullable=False))
    op.add_column('tournaments', sa.Column('min_age', sa.Integer(), nullable=False))
    op.add_column('tournaments', sa.Column('registration_start', sa.TIMESTAMP(), nullable=False))
    op.add_column('tournaments', sa.Column('registration_end', sa.TIMESTAMP(), nullable=False))
    op.add_column('tournaments', sa.Column('tournament_start', sa.TIMESTAMP(), nullable=False))
    op.add_column('tournaments', sa.Column('tournament_end', sa.TIMESTAMP(), nullable=False))
    op.add_column('tournaments', sa.Column('tournament_format', sa.Text(), nullable=False))
    op.add_column('tournaments', sa.Column('participants_number', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tournaments', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'participants_number')
    op.drop_column('tournaments', 'tournament_format')
    op.drop_column('tournaments', 'tournament_end')
    op.drop_column('tournaments', 'tournament_start')
    op.drop_column('tournaments', 'registration_end')
    op.drop_column('tournaments', 'registration_start')
    op.drop_column('tournaments', 'min_age')
    op.drop_column('tournaments', 'game_id')
    # ### end Alembic commands ###
