"""Change user model

Revision ID: 0011
Revises: 0010
Create Date: 2024-07-18 01:20:35.067370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE if exists roles cascade;')
    registration_status = postgresql.ENUM('PLAYER', 'ORGANIZER', 'ADMIN', name='userroles')
    registration_status.create(op.get_bind())
    op.add_column('users', sa.Column('role', sa.Enum('PLAYER', 'ORGANIZER', 'ADMIN', name='userroles'), nullable=True))
    op.execute("UPDATE users SET role='PLAYER';")
    op.alter_column('users', 'role', nullable=False)
    op.alter_column('users', 'country',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'city',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['tg_login'])
    op.create_unique_constraint(None, 'users', ['chat_id'])
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'city',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'country',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'role')
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey')
    )

    registration_status = postgresql.ENUM('PLAYER', 'ORGANIZER', 'ADMIN', name='userroles')
    registration_status.drop(op.get_bind())
    # ### end Alembic commands ###
