"""Add is_used parameter for telegram verifier

Revision ID: 0015
Revises: 0014
Create Date: 2024-07-20 00:50:37.636497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0015'
down_revision: Union[str, None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_token_verifier', sa.Column('is_used', sa.Boolean(), nullable=True))
    op.execute("UPDATE telegram_token_verifier SET is_used=true;")
    op.alter_column('telegram_token_verifier', 'is_used',  nullable=True)
    op.create_unique_constraint(None, 'telegram_token_verifier', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_token_verifier', type_='unique')
    op.drop_column('telegram_token_verifier', 'is_used')
    # ### end Alembic commands ###
