"""Add tournament team model

Revision ID: 0016
Revises: 0015
Create Date: 2024-07-21 19:50:08.367450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0016'
down_revision: Union[str, None] = '0015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_teams',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('telegram_token_verifier', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('tournament_registered_users', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournament_registered_users', 'tournament_teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_registered_users', type_='foreignkey')
    op.drop_column('tournament_registered_users', 'team_id')
    op.alter_column('telegram_token_verifier', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('tournament_teams')
    # ### end Alembic commands ###
