"""Add manual_status field for tournament

Revision ID: 0018
Revises: 0017
Create Date: 2024-07-22 06:44:26.066810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0018'
down_revision: Union[str, None] = '0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    manual_status = postgresql.ENUM('REGISTRATION_OPENED', 'REGISTRATION_CLOSED', 'TOURNAMENT_STARTED', 'TOURNAMENT_ENDED', name='manualtournamentstatus')
    manual_status.create(op.get_bind())
    op.add_column('tournaments', sa.Column('manual_status', sa.Enum('REGISTRATION_OPENED', 'REGISTRATION_CLOSED', 'TOURNAMENT_STARTED', 'TOURNAMENT_ENDED', name='manualtournamentstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'manual_status')

    manual_status = postgresql.ENUM('REGISTRATION_OPENED', 'REGISTRATION_CLOSED', 'TOURNAMENT_STARTED',
                                         'TOURNAMENT_ENDED', name='manualtournamentstatus')
    manual_status.drop(op.get_bind())
    # ### end Alembic commands ###
