"""Add is_team_shown for registration model

Revision ID: 0019
Revises: 0018
Create Date: 2024-07-22 16:39:11.102492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0019'
down_revision: Union[str, None] = '0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_registered_users', sa.Column('is_team_shown', sa.Boolean(), nullable=True))
    op.execute("UPDATE tournament_registered_users SET is_team_shown=false;")
    op.alter_column('tournament_registered_users', 'is_team_shown', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_registered_users', 'is_team_shown')
    # ### end Alembic commands ###
