"""Add logo_id for team model

Revision ID: 0020
Revises: 0019
Create Date: 2024-07-22 17:03:37.007716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0020'
down_revision: Union[str, None] = '0019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_teams', sa.Column('logo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournament_teams', 'uploads', ['logo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_teams', type_='foreignkey')
    op.drop_column('tournament_teams', 'logo_id')
    # ### end Alembic commands ###
