"""Add models for double elimination bracket

Revision ID: 0021
Revises: 0020
Create Date: 2024-07-27 04:47:48.247655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0021'
down_revision: Union[str, None] = '0020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_de_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('short_id', sa.String(), nullable=False),
    sa.Column('branch_type', sa.Enum('WINNER', 'LOSER', name='deseriesbranchtype'), nullable=False),
    sa.Column('state', sa.Enum('NO_PARTY', 'SCORE_DONE', name='deseriesstates'), nullable=False),
    sa.Column('is_bye', sa.Boolean(), nullable=False),
    sa.Column('next_winner_id', sa.UUID(), nullable=True),
    sa.Column('next_loser_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['next_loser_id'], ['tournament_de_series.id'], ),
    sa.ForeignKeyConstraint(['next_winner_id'], ['tournament_de_series.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    manual_status = postgresql.ENUM('DOUBLE_ELIMINATION', name='brackettype')
    manual_status.create(op.get_bind())
    op.add_column('tournaments', sa.Column('bracket_type', sa.Enum('DOUBLE_ELIMINATION', name='brackettype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'bracket_type')
    op.drop_table('tournament_de_series')
    manual_status = postgresql.ENUM('DOUBLE_ELIMINATION', name='brackettype')
    manual_status.drop(op.get_bind())
    # ### end Alembic commands ###
