"""Add links to gamer for series

Revision ID: 0022
Revises: 0021
Create Date: 2024-07-28 06:08:55.660952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0022'
down_revision: Union[str, None] = '0021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_de_series', sa.Column('gamer1_id', sa.Integer(), nullable=True))
    op.add_column('tournament_de_series', sa.Column('gamer2_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournament_de_series', 'gamers', ['gamer1_id'], ['id'])
    op.create_foreign_key(None, 'tournament_de_series', 'gamers', ['gamer2_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_de_series', type_='foreignkey')
    op.drop_constraint(None, 'tournament_de_series', type_='foreignkey')
    op.drop_column('tournament_de_series', 'gamer2_id')
    op.drop_column('tournament_de_series', 'gamer1_id')
    # ### end Alembic commands ###
