"""add_matches

Revision ID: 0022
Revises: 0021
Create Date: 2024-07-27 22:40:32.256633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0023'
down_revision: Union[str, None] = '0022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('de_series_id', sa.UUID(), nullable=False),
    sa.Column('home_player_id', sa.Integer(), nullable=False),
    sa.Column('guest_player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INITIAL_ACTIVE', 'INITIAL_DISABLED', 'WAITING_CONFIRMATION_FROM_HOME_PLAYER', 'WAITING_CONFIRMATION_FROM_GUEST_PLAYER', 'CONTRADICTION_IN_RESULT', 'CONFIRMED', 'NOT_NECESSARY', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['de_series_id'], ['tournament_de_series.id'], ),
    sa.ForeignKeyConstraint(['guest_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['home_player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('guest_score', sa.Integer(), nullable=False),
    sa.Column('video_link', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['series_matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_player_id'), 'match_results', ['player_id'], unique=False)
    op.drop_constraint('tournament_de_series_next_loser_id_fkey', 'tournament_de_series', type_='foreignkey')
    op.drop_constraint('tournament_de_series_next_winner_id_fkey', 'tournament_de_series', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_de_series', sa.Column('next_loser_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tournament_de_series', sa.Column('next_winner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('tournament_de_series_next_winner_id_fkey', 'tournament_de_series', 'tournament_de_series', ['next_winner_id'], ['id'])
    op.create_foreign_key('tournament_de_series_next_loser_id_fkey', 'tournament_de_series', 'tournament_de_series', ['next_loser_id'], ['id'])
    op.drop_index(op.f('ix_match_results_player_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_table('series_matches')
    # ### end Alembic commands ###
