"""add_series_feedbacks

Revision ID: 0023
Revises: 0022
Create Date: 2024-07-28 08:30:50.974857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0024'
down_revision: Union[str, None] = '0023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('de_series_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('opponent_mark', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['de_series_id'], ['tournament_de_series.id'], ),
    sa.ForeignKeyConstraint(['opponent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_feedbacks_author_id'), 'series_feedbacks', ['author_id'], unique=False)
    op.create_index(op.f('ix_series_feedbacks_opponent_id'), 'series_feedbacks', ['opponent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_series_feedbacks_opponent_id'), table_name='series_feedbacks')
    op.drop_index(op.f('ix_series_feedbacks_author_id'), table_name='series_feedbacks')
    op.drop_table('series_feedbacks')
    # ### end Alembic commands ###
