"""Add new fields to series model

Revision ID: 0025
Revises: 0024
Create Date: 2024-07-28 12:54:57.249225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0025'
down_revision: Union[str, None] = '0024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('series_matches', 'home_player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('series_matches', 'guest_player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('series_matches_home_player_id_fkey', 'series_matches', type_='foreignkey')
    op.drop_constraint('series_matches_guest_player_id_fkey', 'series_matches', type_='foreignkey')
    op.create_foreign_key(None, 'series_matches', 'gamers', ['home_player_id'], ['id'])
    op.create_foreign_key(None, 'series_matches', 'gamers', ['guest_player_id'], ['id'])
    op.add_column('tournament_de_series', sa.Column('is_initial', sa.Boolean(), nullable=True))
    op.add_column('tournament_de_series', sa.Column('round', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournament_de_series', 'tournament_de_series', ['next_winner_id'], ['id'])
    op.create_foreign_key(None, 'tournament_de_series', 'tournament_de_series', ['next_loser_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_de_series', type_='foreignkey')
    op.drop_constraint(None, 'tournament_de_series', type_='foreignkey')
    op.drop_column('tournament_de_series', 'round')
    op.drop_column('tournament_de_series', 'is_initial')
    op.drop_constraint(None, 'series_matches', type_='foreignkey')
    op.drop_constraint(None, 'series_matches', type_='foreignkey')
    op.create_foreign_key('series_matches_guest_player_id_fkey', 'series_matches', 'users', ['guest_player_id'], ['id'])
    op.create_foreign_key('series_matches_home_player_id_fkey', 'series_matches', 'users', ['home_player_id'], ['id'])
    op.alter_column('series_matches', 'guest_player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('series_matches', 'home_player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
