"""Add new field for series model

Revision ID: 0028
Revises: 0027
Create Date: 2024-07-28 16:54:55.773831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0028'
down_revision: Union[str, None] = '0027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE deseriesstates ADD VALUE 'PLAYED'")
    op.execute("ALTER TYPE deseriesstates ADD VALUE 'WALK_OVER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
