"""add_organizer_confirm_status

Revision ID: 0030
Revises: 0029
Create Date: 2024-08-02 23:26:28.811536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0030'
down_revision: Union[str, None] = '0029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'matchstatus', ['INITIAL_ACTIVE', 'INITIAL_DISABLED', 'WAITING_CONFIRMATION_FROM_HOME_PLAYER', 'WAITING_CONFIRMATION_FROM_GUEST_PLAYER', 'CONTRADICTION_IN_RESULT', 'CONFIRMED', 'NOT_NECESSARY', 'CONFIRMED_BY_CRON', 'CONFIRMED_BY_ORGANIZER'],
                        [TableReference(table_schema='public', table_name='series_matches', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'matchstatus', ['INITIAL_ACTIVE', 'INITIAL_DISABLED', 'WAITING_CONFIRMATION_FROM_HOME_PLAYER', 'WAITING_CONFIRMATION_FROM_GUEST_PLAYER', 'CONTRADICTION_IN_RESULT', 'CONFIRMED', 'NOT_NECESSARY', 'CONFIRMED_BY_CRON'],
                        [TableReference(table_schema='public', table_name='series_matches', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
