"""add_score_to_series

Revision ID: 0031
Revises: 0030
Create Date: 2024-08-09 11:24:26.142683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0031'
down_revision: Union[str, None] = '0030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_de_series', sa.Column('gamer1_score', sa.Integer(), nullable=True))
    op.add_column('tournament_de_series', sa.Column('gamer2_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_de_series', 'gamer2_score')
    op.drop_column('tournament_de_series', 'gamer1_score')
    # ### end Alembic commands ###
