"""add_match_complaints

Revision ID: 0033
Revises: 0032
Create Date: 2024-08-16 01:22:05.883317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0033'
down_revision: Union[str, None] = '0032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PLAYER_MANUAL', 'AUTO', name='matchcomplaintcreation').create(op.get_bind())
    sa.Enum('OPEN', 'IN_PROGRESS', 'REJECTED', 'CLOSED', name='matchcomplaintstatus').create(op.get_bind())
    op.create_table('match_complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'IN_PROGRESS', 'REJECTED', 'CLOSED', name='matchcomplaintstatus', create_type=False), nullable=False),
    sa.Column('creation_way', postgresql.ENUM('PLAYER_MANUAL', 'AUTO', name='matchcomplaintcreation', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['series_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_complaints_author_id'), 'match_complaints', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_complaints_author_id'), table_name='match_complaints')
    op.drop_table('match_complaints')
    sa.Enum('OPEN', 'IN_PROGRESS', 'REJECTED', 'CLOSED', name='matchcomplaintstatus').drop(op.get_bind())
    sa.Enum('PLAYER_MANUAL', 'AUTO', name='matchcomplaintcreation').drop(op.get_bind())
    # ### end Alembic commands ###
