"""add_resolution_and_series_to_complaints

Revision ID: 0034
Revises: 0033
Create Date: 2024-08-16 01:48:25.020063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0034'
down_revision: Union[str, None] = '0033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_complaints', sa.Column('de_series_id', sa.UUID(), nullable=False))
    op.add_column('match_complaints', sa.Column('resolution_text', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'match_complaints', 'tournament_de_series', ['de_series_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_complaints', type_='foreignkey')
    op.drop_column('match_complaints', 'resolution_text')
    op.drop_column('match_complaints', 'de_series_id')
    # ### end Alembic commands ###
