"""add_tournament_id_to_complaint

Revision ID: 0036
Revises: 0035
Create Date: 2024-08-31 13:23:15.057513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0037'
down_revision: Union[str, None] = '0036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_complaints', sa.Column('tournament_id', sa.Integer(), nullable=False))
    op.drop_index('ix_match_complaints_author_id', table_name='match_complaints')
    op.create_index(op.f('ix_match_complaints_de_series_id'), 'match_complaints', ['de_series_id'], unique=False)
    op.create_index(op.f('ix_match_complaints_match_id'), 'match_complaints', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_complaints_tournament_id'), 'match_complaints', ['tournament_id'], unique=False)
    op.create_foreign_key(None, 'match_complaints', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_complaints', type_='foreignkey')
    op.drop_index(op.f('ix_match_complaints_tournament_id'), table_name='match_complaints')
    op.drop_index(op.f('ix_match_complaints_match_id'), table_name='match_complaints')
    op.drop_index(op.f('ix_match_complaints_de_series_id'), table_name='match_complaints')
    op.create_index('ix_match_complaints_author_id', 'match_complaints', ['author_id'], unique=False)
    op.drop_column('match_complaints', 'tournament_id')
    # ### end Alembic commands ###
