"""Add lifecycle status for tournament model

Revision ID: 0038
Revises: 0037
Create Date: 2024-09-05 00:09:45.811898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0038'
down_revision: Union[str, None] = '0037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('REGISTRATION_NOT_STARTED', 'REGISTRATION_OPENED', 'REGISTRATION_CLOSED', 'TOURNAMENT_STARTED', 'TOURNAMENT_ENDED', 'TOURNAMENT_ARCHIVED', name='lifecycletournamentstatus').create(op.get_bind())
    op.add_column('tournaments', sa.Column('lifecycle_status', postgresql.ENUM('REGISTRATION_NOT_STARTED', 'REGISTRATION_OPENED', 'REGISTRATION_CLOSED', 'TOURNAMENT_STARTED', 'TOURNAMENT_ENDED', 'TOURNAMENT_ARCHIVED', name='lifecycletournamentstatus', create_type=False), nullable=True))
    op.drop_column('tournaments', 'manual_status')
    sa.Enum('REGISTRATION_OPENED', 'REGISTRATION_CLOSED', 'TOURNAMENT_STARTED', 'TOURNAMENT_ENDED', name='manualtournamentstatus').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('REGISTRATION_OPENED', 'REGISTRATION_CLOSED', 'TOURNAMENT_STARTED', 'TOURNAMENT_ENDED', name='manualtournamentstatus').create(op.get_bind())
    op.add_column('tournaments', sa.Column('manual_status', postgresql.ENUM('REGISTRATION_OPENED', 'REGISTRATION_CLOSED', 'TOURNAMENT_STARTED', 'TOURNAMENT_ENDED', name='manualtournamentstatus', create_type=False), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'lifecycle_status')
    sa.Enum('REGISTRATION_NOT_STARTED', 'REGISTRATION_OPENED', 'REGISTRATION_CLOSED', 'TOURNAMENT_STARTED', 'TOURNAMENT_ENDED', 'TOURNAMENT_ARCHIVED', name='lifecycletournamentstatus').drop(op.get_bind())
    # ### end Alembic commands ###
