"""Change tournament structure

Revision ID: 0039
Revises: 0038
Create Date: 2024-10-24 10:14:41.553481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0039'
down_revision: Union[str, None] = '0038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WILDCARD', name='intermediateswissstagetypes').create(op.get_bind())
    sa.Enum('SWISS_CLASSIC', 'SWISS_50_50', 'SWISS_MANUAL', name='swissstagetypes').create(op.get_bind())
    sa.Enum('SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'SWISS', 'LEAGUE', name='tournamentstagetypes').create(op.get_bind())
    sa.Enum('MANUAL', 'REGISTRATION', name='registrationtypes').create(op.get_bind())
    op.create_table('double_elimination_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('final_game_number', sa.Integer(), nullable=False),
    sa.Column('winner_bracket_advantage', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('single_elimination_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swiss_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_type', postgresql.ENUM('SWISS_CLASSIC', 'SWISS_50_50', 'SWISS_MANUAL', name='swissstagetypes', create_type=False), nullable=False),
    sa.Column('add_intermediate', sa.Boolean(), nullable=False),
    sa.Column('intermediate_type', postgresql.ENUM('WILDCARD', name='intermediateswissstagetypes', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('stage_type', postgresql.ENUM('SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'SWISS', 'LEAGUE', name='tournamentstagetypes', create_type=False), nullable=False),
    sa.Column('single_elimination_stage_id', sa.UUID(), nullable=True),
    sa.Column('double_elimination_stage_id', sa.UUID(), nullable=True),
    sa.Column('swiss_stage_id', sa.UUID(), nullable=True),
    sa.Column('league_stage_id', sa.UUID(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['double_elimination_stage_id'], ['double_elimination_stages.id'], ),
    sa.ForeignKeyConstraint(['league_stage_id'], ['league_stages.id'], ),
    sa.ForeignKeyConstraint(['single_elimination_stage_id'], ['single_elimination_stages.id'], ),
    sa.ForeignKeyConstraint(['swiss_stage_id'], ['swiss_stages.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tournaments', sa.Column('registration_type', postgresql.ENUM('MANUAL', 'REGISTRATION', name='registrationtypes', create_type=False), nullable=True))
    op.add_column('tournaments', sa.Column('should_limit_participants', sa.Boolean(), nullable=True))
    op.alter_column('tournaments', 'tournament_format',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tournaments', 'registration_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tournaments', 'registration_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tournaments', 'participants_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tournaments', 'bracket_type')
    sa.Enum('DOUBLE_ELIMINATION', name='brackettype').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DOUBLE_ELIMINATION', name='brackettype').create(op.get_bind())
    op.add_column('tournaments', sa.Column('bracket_type', postgresql.ENUM('DOUBLE_ELIMINATION', name='brackettype', create_type=False), autoincrement=False, nullable=True))
    op.alter_column('tournaments', 'participants_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournaments', 'registration_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('tournaments', 'registration_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('tournaments', 'tournament_format',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('tournaments', 'should_limit_participants')
    op.drop_column('tournaments', 'registration_type')
    op.drop_table('tournament_stages')
    op.drop_table('swiss_stages')
    op.drop_table('single_elimination_stages')
    op.drop_table('league_stages')
    op.drop_table('double_elimination_stages')
    sa.Enum('MANUAL', 'REGISTRATION', name='registrationtypes').drop(op.get_bind())
    sa.Enum('SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'SWISS', 'LEAGUE', name='tournamentstagetypes').drop(op.get_bind())
    sa.Enum('SWISS_CLASSIC', 'SWISS_50_50', 'SWISS_MANUAL', name='swissstagetypes').drop(op.get_bind())
    sa.Enum('WILDCARD', name='intermediateswissstagetypes').drop(op.get_bind())
    # ### end Alembic commands ###
