"""Add fields for tournament images

Revision ID: 0040
Revises: 0039
Create Date: 2024-10-24 15:55:21.009352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0040'
down_revision: Union[str, None] = '0039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('cover_image_id', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('header_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournaments', 'uploads', ['cover_image_id'], ['id'])
    op.create_foreign_key(None, 'tournaments', 'uploads', ['header_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'header_image_id')
    op.drop_column('tournaments', 'cover_image_id')
    # ### end Alembic commands ###
