"""Add models for swiss tournaments

Revision ID: 0041
Revises: 0040
Create Date: 2024-10-31 02:40:06.945631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0041'
down_revision: Union[str, None] = '0040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('STAGE_NOT_STARTED', 'STAGE_STARTED', 'STAGE_ENDED', name='tournamentstagestatus').create(op.get_bind())
    sa.Enum('NOT_ASSIGNED', 'PLAYING', 'PLAYED', name='swissseriesstatus').create(op.get_bind())
    op.create_table('swiss_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('swiss_stage_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['swiss_stage_id'], ['swiss_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swiss_series_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=True),
    sa.Column('wins_number', sa.Integer(), nullable=False),
    sa.Column('loses_number', sa.Integer(), nullable=False),
    sa.Column('participants_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['swiss_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swiss_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swiss_series_group_id', sa.UUID(), nullable=True),
    sa.Column('gamer1_id', sa.Integer(), nullable=True),
    sa.Column('gamer2_id', sa.Integer(), nullable=True),
    sa.Column('gamer1_score', sa.Integer(), nullable=True),
    sa.Column('gamer2_score', sa.Integer(), nullable=True),
    sa.Column('gamers_assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', postgresql.ENUM('NOT_ASSIGNED', 'PLAYING', 'PLAYED', name='swissseriesstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gamer1_id'], ['gamers.id'], ),
    sa.ForeignKeyConstraint(['gamer2_id'], ['gamers.id'], ),
    sa.ForeignKeyConstraint(['swiss_series_group_id'], ['swiss_series_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('series_matches', sa.Column('swiss_series_id', sa.UUID(), nullable=True))
    op.alter_column('series_matches', 'de_series_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'series_matches', 'swiss_series', ['swiss_series_id'], ['id'])
    op.add_column('swiss_stages', sa.Column('wins_needed', sa.Integer(), nullable=True))
    op.add_column('swiss_stages', sa.Column('loses_needed', sa.Integer(), nullable=True))
    op.add_column('tournament_stages', sa.Column('status', postgresql.ENUM('STAGE_NOT_STARTED', 'STAGE_STARTED', 'STAGE_ENDED', name='tournamentstagestatus', create_type=False), nullable=False, server_default='STAGE_NOT_STARTED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_stages', 'status')
    op.drop_column('swiss_stages', 'loses_needed')
    op.drop_column('swiss_stages', 'wins_needed')
    op.drop_constraint(None, 'series_matches', type_='foreignkey')
    op.alter_column('series_matches', 'de_series_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('series_matches', 'swiss_series_id')
    op.drop_table('swiss_series')
    op.drop_table('swiss_series_groups')
    op.drop_table('swiss_rounds')
    sa.Enum('NOT_ASSIGNED', 'PLAYING', 'PLAYED', name='swissseriesstatus').drop(op.get_bind())
    sa.Enum('STAGE_NOT_STARTED', 'STAGE_STARTED', 'STAGE_ENDED', name='tournamentstagestatus').drop(op.get_bind())
    # ### end Alembic commands ###
