"""Add round status for swiss tournament

Revision ID: 0042
Revises: 0041
Create Date: 2024-10-31 07:22:31.205496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0042'
down_revision: Union[str, None] = '0041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ROUND_NOT_STARTED', 'ROUND_STARTED', 'ROUND_ENDED', name='swissstageroundstatuses').create(op.get_bind())
    op.add_column('swiss_rounds', sa.Column('status', postgresql.ENUM('ROUND_NOT_STARTED', 'ROUND_STARTED', 'ROUND_ENDED', name='swissstageroundstatuses', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swiss_rounds', 'status')
    sa.Enum('ROUND_NOT_STARTED', 'ROUND_STARTED', 'ROUND_ENDED', name='swissstageroundstatuses').drop(op.get_bind())
    # ### end Alembic commands ###
