"""Refactor torunaments models

Revision ID: 0043
Revises: 0042
Create Date: 2024-11-01 11:56:38.306585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0043'
down_revision: Union[str, None] = '0042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gamer1_id', sa.Integer(), nullable=True),
    sa.Column('gamer2_id', sa.Integer(), nullable=True),
    sa.Column('gamer1_score', sa.Integer(), nullable=True),
    sa.Column('gamer2_score', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gamer1_id'], ['gamers.id'], ),
    sa.ForeignKeyConstraint(['gamer2_id'], ['gamers.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_tournament_id'), 'series', ['tournament_id'], unique=False)
    op.add_column('double_elimination_stages', sa.Column('stage_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'double_elimination_stages', 'tournament_stages', ['stage_id'], ['id'])
    op.add_column('league_stages', sa.Column('stage_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'league_stages', 'tournament_stages', ['stage_id'], ['id'])
    op.add_column('match_complaints', sa.Column('series_id', sa.UUID(), nullable=True))
    op.drop_index('ix_match_complaints_de_series_id', table_name='match_complaints')
    op.create_index(op.f('ix_match_complaints_series_id'), 'match_complaints', ['series_id'], unique=False)
    op.drop_constraint('match_complaints_de_series_id_fkey', 'match_complaints', type_='foreignkey')
    op.create_foreign_key(None, 'match_complaints', 'series', ['series_id'], ['id'])
    op.drop_column('match_complaints', 'de_series_id')
    op.add_column('series_feedbacks', sa.Column('series_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_series_feedbacks_series_id'), 'series_feedbacks', ['series_id'], unique=False)
    op.drop_constraint('series_feedbacks_de_series_id_fkey', 'series_feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'series_feedbacks', 'series', ['series_id'], ['id'])
    op.drop_column('series_feedbacks', 'de_series_id')
    op.add_column('series_matches', sa.Column('series_id', sa.UUID(), nullable=True))
    op.drop_constraint('series_matches_de_series_id_fkey', 'series_matches', type_='foreignkey')
    op.drop_constraint('series_matches_swiss_series_id_fkey', 'series_matches', type_='foreignkey')
    op.create_foreign_key(None, 'series_matches', 'series', ['series_id'], ['id'])
    op.drop_column('series_matches', 'swiss_series_id')
    op.drop_column('series_matches', 'de_series_id')
    op.add_column('single_elimination_stages', sa.Column('stage_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'single_elimination_stages', 'tournament_stages', ['stage_id'], ['id'])
    op.add_column('swiss_series', sa.Column('series_id', sa.UUID(), nullable=True))
    op.drop_constraint('swiss_series_gamer2_id_fkey', 'swiss_series', type_='foreignkey')
    op.drop_constraint('swiss_series_gamer1_id_fkey', 'swiss_series', type_='foreignkey')
    op.create_foreign_key(None, 'swiss_series', 'series', ['series_id'], ['id'])
    op.drop_column('swiss_series', 'gamers_assigned_at')
    op.drop_column('swiss_series', 'gamer1_score')
    op.drop_column('swiss_series', 'gamer2_id')
    op.drop_column('swiss_series', 'gamer1_id')
    op.drop_column('swiss_series', 'gamer2_score')
    op.add_column('swiss_stages', sa.Column('stage_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'swiss_stages', 'tournament_stages', ['stage_id'], ['id'])
    op.drop_constraint('tournament_de_series_gamer1_id_fkey', 'tournament_de_series', type_='foreignkey')
    op.drop_constraint('tournament_de_series_gamer2_id_fkey', 'tournament_de_series', type_='foreignkey')
    op.drop_column('tournament_de_series', 'gamers_assigned_at')
    op.drop_column('tournament_de_series', 'gamer1_score')
    op.drop_column('tournament_de_series', 'gamer2_id')
    op.drop_column('tournament_de_series', 'gamer1_id')
    op.drop_column('tournament_de_series', 'gamer2_score')
    op.drop_column('tournament_de_series', 'series_id')
    op.drop_constraint('tournament_stages_league_stage_id_fkey', 'tournament_stages', type_='foreignkey')
    op.drop_constraint('tournament_stages_double_elimination_stage_id_fkey', 'tournament_stages', type_='foreignkey')
    op.drop_constraint('tournament_stages_swiss_stage_id_fkey', 'tournament_stages', type_='foreignkey')
    op.drop_constraint('tournament_stages_single_elimination_stage_id_fkey', 'tournament_stages', type_='foreignkey')
    op.drop_column('tournament_stages', 'swiss_stage_id')
    op.drop_column('tournament_stages', 'double_elimination_stage_id')
    op.drop_column('tournament_stages', 'single_elimination_stage_id')
    op.drop_column('tournament_stages', 'league_stage_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_stages', sa.Column('league_stage_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tournament_stages', sa.Column('single_elimination_stage_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tournament_stages', sa.Column('double_elimination_stage_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tournament_stages', sa.Column('swiss_stage_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('tournament_stages_single_elimination_stage_id_fkey', 'tournament_stages', 'single_elimination_stages', ['single_elimination_stage_id'], ['id'])
    op.create_foreign_key('tournament_stages_swiss_stage_id_fkey', 'tournament_stages', 'swiss_stages', ['swiss_stage_id'], ['id'])
    op.create_foreign_key('tournament_stages_double_elimination_stage_id_fkey', 'tournament_stages', 'double_elimination_stages', ['double_elimination_stage_id'], ['id'])
    op.create_foreign_key('tournament_stages_league_stage_id_fkey', 'tournament_stages', 'league_stages', ['league_stage_id'], ['id'])
    op.add_column('tournament_de_series', sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tournament_de_series', sa.Column('gamer2_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tournament_de_series', sa.Column('gamer1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tournament_de_series', sa.Column('gamer2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tournament_de_series', sa.Column('gamer1_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tournament_de_series', sa.Column('gamers_assigned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key('tournament_de_series_gamer2_id_fkey', 'tournament_de_series', 'gamers', ['gamer2_id'], ['id'])
    op.create_foreign_key('tournament_de_series_gamer1_id_fkey', 'tournament_de_series', 'gamers', ['gamer1_id'], ['id'])
    op.drop_constraint(None, 'swiss_stages', type_='foreignkey')
    op.drop_column('swiss_stages', 'stage_id')
    op.add_column('swiss_series', sa.Column('gamer2_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('swiss_series', sa.Column('gamer1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('swiss_series', sa.Column('gamer2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('swiss_series', sa.Column('gamer1_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('swiss_series', sa.Column('gamers_assigned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'swiss_series', type_='foreignkey')
    op.create_foreign_key('swiss_series_gamer1_id_fkey', 'swiss_series', 'gamers', ['gamer1_id'], ['id'])
    op.create_foreign_key('swiss_series_gamer2_id_fkey', 'swiss_series', 'gamers', ['gamer2_id'], ['id'])
    op.drop_column('swiss_series', 'series_id')
    op.drop_constraint(None, 'single_elimination_stages', type_='foreignkey')
    op.drop_column('single_elimination_stages', 'stage_id')
    op.add_column('series_matches', sa.Column('de_series_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('series_matches', sa.Column('swiss_series_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'series_matches', type_='foreignkey')
    op.create_foreign_key('series_matches_swiss_series_id_fkey', 'series_matches', 'swiss_series', ['swiss_series_id'], ['id'])
    op.create_foreign_key('series_matches_de_series_id_fkey', 'series_matches', 'tournament_de_series', ['de_series_id'], ['id'])
    op.drop_column('series_matches', 'series_id')
    op.add_column('series_feedbacks', sa.Column('de_series_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'series_feedbacks', type_='foreignkey')
    op.create_foreign_key('series_feedbacks_de_series_id_fkey', 'series_feedbacks', 'tournament_de_series', ['de_series_id'], ['id'])
    op.drop_index(op.f('ix_series_feedbacks_series_id'), table_name='series_feedbacks')
    op.drop_column('series_feedbacks', 'series_id')
    op.add_column('match_complaints', sa.Column('de_series_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'match_complaints', type_='foreignkey')
    op.create_foreign_key('match_complaints_de_series_id_fkey', 'match_complaints', 'tournament_de_series', ['de_series_id'], ['id'])
    op.drop_index(op.f('ix_match_complaints_series_id'), table_name='match_complaints')
    op.create_index('ix_match_complaints_de_series_id', 'match_complaints', ['de_series_id'], unique=False)
    op.drop_column('match_complaints', 'series_id')
    op.drop_constraint(None, 'league_stages', type_='foreignkey')
    op.drop_column('league_stages', 'stage_id')
    op.drop_constraint(None, 'double_elimination_stages', type_='foreignkey')
    op.drop_column('double_elimination_stages', 'stage_id')
    op.drop_index(op.f('ix_series_tournament_id'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
