"""Refactor de model

Revision ID: 0044
Revises: 0043
Create Date: 2024-11-01 11:56:58.435134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0044'
down_revision: Union[str, None] = '0043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_de_series', sa.Column('series_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tournament_de_series', 'series', ['series_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_de_series', type_='foreignkey')
    op.drop_column('tournament_de_series', 'series_id')
    # ### end Alembic commands ###
