"""Add stage_id to series model

Revision ID: 0045
Revises: 0044
Create Date: 2024-11-01 18:04:04.870093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0045'
down_revision: Union[str, None] = '0044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('stage_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_series_stage_id'), 'series', ['stage_id'], unique=False)
    op.create_foreign_key(None, 'series', 'tournament_stages', ['stage_id'], ['id'])
    op.add_column('series_matches', sa.Column('tournament_id', sa.Integer(), nullable=True))
    op.add_column('series_matches', sa.Column('stage_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_series_matches_tournament_id'), 'series_matches', ['tournament_id'], unique=False)
    op.create_foreign_key(None, 'series_matches', 'tournaments', ['tournament_id'], ['id'])
    op.create_foreign_key(None, 'series_matches', 'tournament_stages', ['stage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'series_matches', type_='foreignkey')
    op.drop_constraint(None, 'series_matches', type_='foreignkey')
    op.drop_index(op.f('ix_series_matches_tournament_id'), table_name='series_matches')
    op.drop_column('series_matches', 'stage_id')
    op.drop_column('series_matches', 'tournament_id')
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.drop_index(op.f('ix_series_stage_id'), table_name='series')
    op.drop_column('series', 'stage_id')
    # ### end Alembic commands ###
