"""Add status for series

Revision ID: 0047
Revises: 0046
Create Date: 2024-11-03 09:42:50.238868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0047'
down_revision: Union[str, None] = '0046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NOT_ASSIGNED', 'PLAYING', 'PLAYED', name='seriesstatus').create(op.get_bind())
    op.add_column('series', sa.Column('status', postgresql.ENUM('NOT_ASSIGNED', 'PLAYING', 'PLAYED', name='seriesstatus', create_type=False), server_default='NOT_ASSIGNED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swiss_series', 'status',
               existing_type=postgresql.ENUM('NOT_ASSIGNED', 'PLAYING', 'PLAYED', name='swissseriesstatus'),
               nullable=True)
    op.drop_column('series', 'status')
    sa.Enum('NOT_ASSIGNED', 'PLAYING', 'PLAYED', name='seriesstatus').drop(op.get_bind())
    # ### end Alembic commands ###
