"""Add new statuses for round

Revision ID: 0048
Revises: 0047
Create Date: 2024-11-07 16:13:06.418889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0048'
down_revision: Union[str, None] = '0047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'swissstageroundstatuses', ['ROUND_NOT_STARTED', 'WAITING_FOR_DRAW', 'DRAW_STARTED', 'WAITING_FOR_START', 'ROUND_STARTED', 'ROUND_ENDED'],
                        [TableReference(table_schema='public', table_name='swiss_rounds', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'swissstageroundstatuses', ['ROUND_NOT_STARTED', 'ROUND_STARTED', 'ROUND_ENDED'],
                        [TableReference(table_schema='public', table_name='swiss_rounds', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
