"""Add new status for series

Revision ID: 0050
Revises: 0049
Create Date: 2024-11-25 03:15:21.854636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0050'
down_revision: Union[str, None] = '0049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'seriesstatus', ['NOT_ASSIGNED', 'PLAYING', 'PLAYED', 'WALK_OVER'],
                        [TableReference(table_schema='public', table_name='series', column_name='status', existing_server_default="'NOT_ASSIGNED'::seriesstatus")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'seriesstatus', ['NOT_ASSIGNED', 'PLAYING', 'PLAYED'],
                        [TableReference(table_schema='public', table_name='series', column_name='status', existing_server_default="'NOT_ASSIGNED'::seriesstatus")],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
