"""Add wildcard stage

Revision ID: 0051
Revises: 0050
Create Date: 2024-12-01 15:39:27.754864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0051'
down_revision: Union[str, None] = '0050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wildcard_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['tournament_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('swiss_stages', 'add_intermediate')
    op.drop_column('swiss_stages', 'intermediate_type')
    sa.Enum('WILDCARD', name='intermediateswissstagetypes').drop(op.get_bind())
    op.sync_enum_values('public', 'tournamentstagetypes', ['SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'SWISS', 'LEAGUE', 'WILDCARD'],
                        [TableReference(table_schema='public', table_name='tournament_stages', column_name='stage_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'tournamentstagetypes', ['SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'SWISS', 'LEAGUE'],
                        [TableReference(table_schema='public', table_name='tournament_stages', column_name='stage_type')],
                        enum_values_to_rename=[])
    sa.Enum('WILDCARD', name='intermediateswissstagetypes').create(op.get_bind())
    op.add_column('swiss_stages', sa.Column('intermediate_type', postgresql.ENUM('WILDCARD', name='intermediateswissstagetypes', create_type=False), autoincrement=False, nullable=True))
    op.add_column('swiss_stages', sa.Column('add_intermediate', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('wildcard_stages')
    # ### end Alembic commands ###
