"""Add wildcard round model

Revision ID: 0052
Revises: 0051
Create Date: 2024-12-01 17:36:50.474211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0052'
down_revision: Union[str, None] = '0051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ROUND_NOT_STARTED', 'WAITING_FOR_START', 'ROUND_STARTED', 'ROUND_ENDED', name='wildcardstageroundstatuses').create(op.get_bind())
    op.create_table('wildcard_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('ROUND_NOT_STARTED', 'WAITING_FOR_START', 'ROUND_STARTED', 'ROUND_ENDED', name='wildcardstageroundstatuses', create_type=False), nullable=True),
    sa.Column('wildcard_stage_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['wildcard_stage_id'], ['wildcard_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wildcard_rounds')
    sa.Enum('ROUND_NOT_STARTED', 'WAITING_FOR_DRAW', 'DRAW_STARTED', 'WAITING_FOR_START', 'ROUND_STARTED', 'ROUND_ENDED', name='wildcardstageroundstatuses').drop(op.get_bind())
    # ### end Alembic commands ###
