"""Add wildcard series model

Revision ID: 0053
Revises: 0052
Create Date: 2024-12-01 18:25:26.285436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0053'
down_revision: Union[str, None] = '0052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wildcard_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('wildcard_round_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['wildcard_round_id'], ['wildcard_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('double_elimination_stages', sa.Column('participant_number', sa.Integer(), nullable=True))
    op.execute("UPDATE double_elimination_stages SET participant_number = 0")
    op.alter_column('double_elimination_stages', 'participant_number', nullable=False)
    op.drop_column('swiss_series', 'status')
    sa.Enum('NOT_ASSIGNED', 'PLAYING', 'PLAYED', name='swissseriesstatus').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NOT_ASSIGNED', 'PLAYING', 'PLAYED', name='swissseriesstatus').create(op.get_bind())
    op.add_column('swiss_series', sa.Column('status', postgresql.ENUM('NOT_ASSIGNED', 'PLAYING', 'PLAYED', name='swissseriesstatus', create_type=False), autoincrement=False, nullable=True))
    op.drop_column('double_elimination_stages', 'participant_number')
    op.drop_table('wildcard_series')
    # ### end Alembic commands ###
