"""Add double elimination models

Revision ID: 0055
Revises: 0054
Create Date: 2024-12-04 18:49:51.979807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0055'
down_revision: Union[str, None] = '0054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ROUND_NOT_STARTED', 'WAITING_FOR_START', 'ROUND_STARTED', 'ROUND_ENDED', name='doubleeliminationstageroundstatuses').create(op.get_bind())
    op.create_table('de_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('ROUND_NOT_STARTED', 'WAITING_FOR_START', 'ROUND_STARTED', 'ROUND_ENDED', name='doubleeliminationstageroundstatuses', create_type=False), nullable=True),
    sa.Column('de_stage_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['de_stage_id'], ['double_elimination_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tournament_de_series', sa.Column('de_round_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tournament_de_series', 'de_rounds', ['de_round_id'], ['id'])
    op.drop_column('tournament_de_series', 'round')
    op.drop_column('tournament_de_series', 'state')
    op.drop_column('tournament_de_series', 'is_initial')
    sa.Enum('NO_PARTY', 'SCORE_DONE', 'PLAYED', 'WALK_OVER', name='deseriesstates').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NO_PARTY', 'SCORE_DONE', 'PLAYED', 'WALK_OVER', name='deseriesstates').create(op.get_bind())
    op.add_column('tournament_de_series', sa.Column('is_initial', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tournament_de_series', sa.Column('state', postgresql.ENUM('NO_PARTY', 'SCORE_DONE', 'PLAYED', 'WALK_OVER', name='deseriesstates', create_type=False), autoincrement=False, nullable=False))
    op.add_column('tournament_de_series', sa.Column('round', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tournament_de_series', type_='foreignkey')
    op.drop_column('tournament_de_series', 'de_round_id')
    op.drop_table('de_rounds')
    sa.Enum('ROUND_NOT_STARTED', 'WAITING_FOR_START', 'ROUND_STARTED', 'ROUND_ENDED', name='doubleeliminationstageroundstatuses').drop(op.get_bind())
    # ### end Alembic commands ###
