"""Change de format

Revision ID: 0056
Revises: 0055
Create Date: 2024-12-05 13:02:01.276434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0056'
down_revision: Union[str, None] = '0055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WINNER', 'LOSER', name='deseriesroundbranchtype').create(op.get_bind())
    op.add_column('de_rounds', sa.Column('branch_type', postgresql.ENUM('WINNER', 'LOSER', name='deseriesroundbranchtype', create_type=False), nullable=False))
    op.add_column('tournament_de_series', sa.Column('round_id', sa.UUID(), nullable=True))
    op.drop_constraint('tournament_de_series_de_round_id_fkey', 'tournament_de_series', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_de_series', 'de_rounds', ['round_id'], ['id'])
    op.drop_column('tournament_de_series', 'is_bye')
    op.drop_column('tournament_de_series', 'branch_type')
    op.drop_column('tournament_de_series', 'de_round_id')
    sa.Enum('WINNER', 'LOSER', name='deseriesbranchtype').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WINNER', 'LOSER', name='deseriesbranchtype').create(op.get_bind())
    op.add_column('tournament_de_series', sa.Column('de_round_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tournament_de_series', sa.Column('branch_type', postgresql.ENUM('WINNER', 'LOSER', name='deseriesbranchtype', create_type=False), autoincrement=False, nullable=False))
    op.add_column('tournament_de_series', sa.Column('is_bye', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tournament_de_series', type_='foreignkey')
    op.create_foreign_key('tournament_de_series_de_round_id_fkey', 'tournament_de_series', 'de_rounds', ['de_round_id'], ['id'])
    op.drop_column('tournament_de_series', 'round_id')
    op.drop_column('de_rounds', 'branch_type')
    sa.Enum('WINNER', 'LOSER', name='deseriesroundbranchtype').drop(op.get_bind())
    # ### end Alembic commands ###
