"""Change de format

Revision ID: 0057
Revises: 0056
Create Date: 2024-12-05 13:22:56.222641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0057'
down_revision: Union[str, None] = '0056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tournament_de_series_tournament_id_fkey', 'tournament_de_series', type_='foreignkey')
    op.drop_column('tournament_de_series', 'tournament_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_de_series', sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tournament_de_series_tournament_id_fkey', 'tournament_de_series', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###
