"""Add model for stage participant

Revision ID: 0058
Revises: 0057
Create Date: 2024-12-05 17:08:26.876228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0058'
down_revision: Union[str, None] = '0057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PLAYING', 'WINNER', 'LOSER', name='stageparticipantstatus').create(op.get_bind())
    op.create_table('stage_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PLAYING', 'WINNER', 'LOSER', name='stageparticipantstatus', create_type=False), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['gamers.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['tournament_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_participants')
    sa.Enum('PLAYING', 'WINNER', 'LOSER', name='stageparticipantstatus').drop(op.get_bind())
    # ### end Alembic commands ###
