"""Change de structure

Revision ID: 0059
Revises: 0058
Create Date: 2024-12-05 19:25:32.591237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0059'
down_revision: Union[str, None] = '0058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WINNER', 'LOSER', name='deseriesbranchtype').create(op.get_bind())
    op.drop_column('de_rounds', 'branch_type')
    op.add_column('tournament_de_series', sa.Column('branch_type', postgresql.ENUM('WINNER', 'LOSER', name='deseriesbranchtype', create_type=False), nullable=True))
    sa.Enum('WINNER', 'LOSER', name='deseriesroundbranchtype').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WINNER', 'LOSER', name='deseriesroundbranchtype').create(op.get_bind())
    op.drop_column('tournament_de_series', 'branch_type')
    op.add_column('de_rounds', sa.Column('branch_type', postgresql.ENUM('WINNER', 'LOSER', name='deseriesroundbranchtype', create_type=False), autoincrement=False, nullable=False))
    sa.Enum('WINNER', 'LOSER', name='deseriesbranchtype').drop(op.get_bind())
    # ### end Alembic commands ###
