"""Add role models

Revision ID: 0060
Revises: 0059
Create Date: 2025-01-08 02:21:31.064263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0060'
down_revision: Union[str, None] = '0059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ADMIN', name='systemroletypes').create(op.get_bind())
    sa.Enum('ORGANIZER', 'MODERATOR', name='tournamentroletypes').create(op.get_bind())
    op.create_table('system_user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_type', postgresql.ENUM('ADMIN', name='systemroletypes', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('role_type', postgresql.ENUM('ORGANIZER', 'MODERATOR', name='tournamentroletypes', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_user_roles')
    op.drop_table('system_user_roles')
    sa.Enum('ORGANIZER', 'MODERATOR', name='tournamentroletypes').drop(op.get_bind())
    sa.Enum('ADMIN', name='systemroletypes').drop(op.get_bind())
    # ### end Alembic commands ###
