"""add new fields in tournament model

Revision ID: 0062
Revises: 0061
Create Date: 2025-01-14 09:23:32.553719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0062'
down_revision: Union[str, None] = '0061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ORGANIZER', 'MODERATOR', name='communityroletypes').create(op.get_bind())
    op.create_table('community_user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('role_type', postgresql.ENUM('ORGANIZER', 'MODERATOR', name='communityroletypes', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('double_elimination_stages', 'participant_number')
    op.add_column('tournaments', sa.Column('community_id', sa.UUID(), nullable=True))
    op.add_column('tournaments', sa.Column('is_primary', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'tournaments', 'communities', ['community_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'is_primary')
    op.drop_column('tournaments', 'community_id')
    op.add_column('double_elimination_stages', sa.Column('participant_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('community_user_roles')
    sa.Enum('ORGANIZER', 'MODERATOR', name='communityroletypes').drop(op.get_bind())
    # ### end Alembic commands ###
