"""Add system roles

Revision ID: 0063
Revises: 0062
Create Date: 2025-01-14 12:48:53.126149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0063'
down_revision: Union[str, None] = '0062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'systemroletypes', ['ADMIN', 'TOURNAMENT_CREATOR', 'COMMUNITY_CREATOR'],
                        [TableReference(table_schema='public', table_name='system_user_roles', column_name='role_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'systemroletypes', ['ADMIN'],
                        [TableReference(table_schema='public', table_name='system_user_roles', column_name='role_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
