"""Add new status for double elimination round

Revision ID: 0064
Revises: 0063
Create Date: 2025-01-14 13:28:20.610700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0064'
down_revision: Union[str, None] = '0063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'doubleeliminationstageroundstatuses', ['ROUND_NOT_STARTED', 'WAITING_FOR_START', 'ROUND_STARTED', 'ROUND_ENDED', 'WAITING_FOR_DRAW'],
                        [TableReference(table_schema='public', table_name='de_rounds', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'doubleeliminationstageroundstatuses', ['ROUND_NOT_STARTED', 'WAITING_FOR_START', 'ROUND_STARTED', 'ROUND_ENDED'],
                        [TableReference(table_schema='public', table_name='de_rounds', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
