"""Add payment type for tournament

Revision ID: 0065
Revises: 0064
Create Date: 2025-01-14 16:00:14.720354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0065'
down_revision: Union[str, None] = '0064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('FREE', 'PAYED', 'PAYED_COMMUNITY', name='tournamentpaymenttype').create(op.get_bind())
    op.add_column('tournaments', sa.Column('payment_type', postgresql.ENUM('FREE', 'PAYED', 'PAYED_COMMUNITY', name='tournamentpaymenttype', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'payment_type')
    sa.Enum('FREE', 'PAYED', 'PAYED_COMMUNITY', name='tournamentpaymenttype').drop(op.get_bind())
    # ### end Alembic commands ###
