"""Add slug to community

Revision ID: 0066
Revises: 0065
Create Date: 2025-01-19 17:54:11.900263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0066'
down_revision: Union[str, None] = '0065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('slug', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'communities', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'communities', type_='unique')
    op.drop_column('communities', 'slug')
    # ### end Alembic commands ###
