"""Add tables for single elimination stage

Revision ID: 0069
Revises: 0068
Create Date: 2025-03-17 17:25:56.595908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0069'
down_revision: Union[str, None] = '0068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ROUND_NOT_STARTED', 'WAITING_FOR_START', 'ROUND_STARTED', 'ROUND_ENDED', 'WAITING_FOR_DRAW', 'DRAW_STARTED', name='singleeliminationstageroundstatuses').create(op.get_bind())
    op.create_table('se_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('ROUND_NOT_STARTED', 'WAITING_FOR_START', 'ROUND_STARTED', 'ROUND_ENDED', 'WAITING_FOR_DRAW', 'DRAW_STARTED', name='singleeliminationstageroundstatuses', create_type=False), nullable=True),
    sa.Column('se_stage_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['se_stage_id'], ['single_elimination_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('se_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('short_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=True),
    sa.Column('next_winner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['next_winner_id'], ['se_series.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['se_rounds.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('single_elimination_stages', sa.Column('game_number', sa.Integer(), nullable=False))
    op.add_column('single_elimination_stages', sa.Column('final_game_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('single_elimination_stages', 'final_game_number')
    op.drop_column('single_elimination_stages', 'game_number')
    op.drop_table('se_series')
    op.drop_table('se_rounds')
    sa.Enum('ROUND_NOT_STARTED', 'WAITING_FOR_START', 'ROUND_STARTED', 'ROUND_ENDED', 'WAITING_FOR_DRAW', 'DRAW_STARTED', name='singleeliminationstageroundstatuses').drop(op.get_bind())
    # ### end Alembic commands ###
