"""Add forecast competition models

Revision ID: 0072
Revises: 0071
Create Date: 2025-04-26 17:04:06.599002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0072'
down_revision: Union[str, None] = '0071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_competition_bets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['gamers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tournaments', sa.Column('is_forecast_competition_allowed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'is_forecast_competition_allowed')
    op.drop_table('forecast_competition_bets')
    # ### end Alembic commands ###
