"""Add tournament access type for teams

Revision ID: 0074
Revises: 0073
Create Date: 2025-07-04 18:03:12.322223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0074'
down_revision: Union[str, None] = '0073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teams_source_team_id_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'teams', ['source_team_id'], ['id'], ondelete='SET NULL')
    op.sync_enum_values('public', 'teamaccesstypes', ['PUBLIC', 'PRIVATE', 'TOURNAMENT'],
                        [TableReference(table_schema='public', table_name='teams', column_name='access_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'teamaccesstypes', ['PUBLIC', 'PRIVATE'],
                        [TableReference(table_schema='public', table_name='teams', column_name='access_type')],
                        enum_values_to_rename=[])
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_source_team_id_fkey', 'teams', 'teams', ['source_team_id'], ['id'])
    # ### end Alembic commands ###
