"""Add flag to use teams logic in tournament model

Revision ID: 0075
Revises: 0074
Create Date: 2025-07-04 18:33:30.495530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import false

# revision identifiers, used by Alembic.
revision: str = '0075'
down_revision: Union[str, None] = '0074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('teams_used', sa.Boolean(), nullable=False, server_default=false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'teams_used')
    # ### end Alembic commands ###
