"""Add TOURNAMENT_INTERNAL to teams access_type

Revision ID: 0076
Revises: 0075
Create Date: 2025-07-05 22:13:06.715063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0076'
down_revision: Union[str, None] = '0075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'teamaccesstypes', ['PUBLIC', 'PRIVATE', 'TOURNAMENT', 'TOURNAMENT_INTERNAL'],
                        [TableReference(table_schema='public', table_name='teams', column_name='access_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'teamaccesstypes', ['PUBLIC', 'PRIVATE', 'TOURNAMENT'],
                        [TableReference(table_schema='public', table_name='teams', column_name='access_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
