"""Remove legacy team relation in participant

Revision ID: 0077
Revises: 0076
Create Date: 2025-07-05 22:33:30.978301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0077'
down_revision: Union[str, None] = '0076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tournament_registered_users_team_id_fkey', 'tournament_registered_users', type_='foreignkey')
    op.drop_column('tournament_registered_users', 'team_id')
    op.drop_column('tournament_registered_users', 'is_team_shown')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_registered_users', sa.Column('is_team_shown', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('tournament_registered_users', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tournament_registered_users_team_id_fkey', 'tournament_registered_users', 'tournament_teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
