"""Remove legacy teams model

Revision ID: 0078
Revises: 0077
Create Date: 2025-07-05 22:34:18.805960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0078'
down_revision: Union[str, None] = '0077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_teams',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('logo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='tournament_teams_creator_id_fkey'),
    sa.ForeignKeyConstraint(['logo_id'], ['uploads.id'], name='tournament_teams_logo_id_fkey'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name='tournament_teams_tournament_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tournament_teams_pkey')
    )
    # ### end Alembic commands ###
