"""Add new team relation for participant

Revision ID: 0079
Revises: 0078
Create Date: 2025-07-05 22:41:21.477365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0079'
down_revision: Union[str, None] = '0078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_registered_users', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tournament_registered_users', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_registered_users', type_='foreignkey')
    op.drop_column('tournament_registered_users', 'team_id')
    # ### end Alembic commands ###
