"""Add new statuses for team draw in tournament

Revision ID: 0080
Revises: 0079
Create Date: 2025-07-06 01:32:05.636090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0080'
down_revision: Union[str, None] = '0079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'lifecycletournamentstatus', ['REGISTRATION_NOT_STARTED', 'REGISTRATION_OPENED', 'REGISTRATION_CLOSED', 'TOURNAMENT_STARTED', 'TOURNAMENT_ENDED', 'TOURNAMENT_ARCHIVED', 'TEAM_DRAW_STARTED', 'TEAM_DRAW_ENDED'],
                        [TableReference(table_schema='public', table_name='tournaments', column_name='lifecycle_status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'lifecycletournamentstatus', ['REGISTRATION_NOT_STARTED', 'REGISTRATION_OPENED', 'REGISTRATION_CLOSED', 'TOURNAMENT_STARTED', 'TOURNAMENT_ENDED', 'TOURNAMENT_ARCHIVED'],
                        [TableReference(table_schema='public', table_name='tournaments', column_name='lifecycle_status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
