"""Add auction handling

Revision ID: 0081
Revises: 0080
Create Date: 2025-07-17 03:10:42.740793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0081'
down_revision: Union[str, None] = '0080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_bets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bet', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['tournament_registered_users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('teams', sa.Column('auction_deadline', sa.DateTime(), nullable=True))
    op.add_column('tournaments', sa.Column('bet_step', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('min_bet', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('max_bet', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('bet_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('bet_extension_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'bet_extension_seconds')
    op.drop_column('tournaments', 'bet_duration_seconds')
    op.drop_column('tournaments', 'max_bet')
    op.drop_column('tournaments', 'min_bet')
    op.drop_column('tournaments', 'bet_step')
    op.drop_column('teams', 'auction_deadline')
    op.drop_table('auction_bets')
    # ### end Alembic commands ###
