"""Add models for broadcasting websocket messages

Revision ID: 0082
Revises: 0081
Create Date: 2025-07-18 00:13:56.730216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0082'
down_revision: Union[str, None] = '0081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websocket_team_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websocket_team_messages_tournament_id'), 'websocket_team_messages', ['tournament_id'], unique=False)
    op.create_table('websocket_team_message_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['websocket_team_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websocket_team_message_deliveries_message_id'), 'websocket_team_message_deliveries', ['message_id'], unique=False)
    op.create_index(op.f('ix_websocket_team_message_deliveries_worker_id'), 'websocket_team_message_deliveries', ['worker_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websocket_team_message_deliveries_worker_id'), table_name='websocket_team_message_deliveries')
    op.drop_index(op.f('ix_websocket_team_message_deliveries_message_id'), table_name='websocket_team_message_deliveries')
    op.drop_table('websocket_team_message_deliveries')
    op.drop_index(op.f('ix_websocket_team_messages_tournament_id'), table_name='websocket_team_messages')
    op.drop_table('websocket_team_messages')
    # ### end Alembic commands ###
