"""Add participant to series and matches

Revision ID: 0085
Revises: 0084
Create Date: 2025-07-31 07:24:16.748423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0085'
down_revision: Union[str, None] = '0084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('participant1_id', sa.Integer(), nullable=True))
    op.add_column('series', sa.Column('participant2_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'series', 'tournament_registered_users', ['participant1_id'], ['id'])
    op.create_foreign_key(None, 'series', 'tournament_registered_users', ['participant2_id'], ['id'])
    op.add_column('series_matches', sa.Column('home_participant_id', sa.Integer(), nullable=True))
    op.add_column('series_matches', sa.Column('guest_participant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'series_matches', 'tournament_registered_users', ['home_participant_id'], ['id'])
    op.create_foreign_key(None, 'series_matches', 'tournament_registered_users', ['guest_participant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'series_matches', type_='foreignkey')
    op.drop_constraint(None, 'series_matches', type_='foreignkey')
    op.drop_column('series_matches', 'guest_participant_id')
    op.drop_column('series_matches', 'home_participant_id')
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.drop_column('series', 'participant2_id')
    op.drop_column('series', 'participant1_id')
    # ### end Alembic commands ###
