"""Add new fields for game

Revision ID: 0086
Revises: 0085
Create Date: 2026-01-30 00:48:32.095262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0086'
down_revision: Union[str, None] = '0085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('min_age', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('disclaimer', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('legal_info', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('cover_image_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('header_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'uploads', ['cover_image_id'], ['id'])
    op.create_foreign_key(None, 'games', 'uploads', ['header_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'header_image_id')
    op.drop_column('games', 'cover_image_id')
    op.drop_column('games', 'legal_info')
    op.drop_column('games', 'disclaimer')
    op.drop_column('games', 'min_age')
    # ### end Alembic commands ###
