"""Remove extra field for image

Revision ID: 0087
Revises: 0086
Create Date: 2026-01-30 00:55:20.379737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0087'
down_revision: Union[str, None] = '0086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_header_image_id_fkey', 'games', type_='foreignkey')
    op.drop_column('games', 'header_image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('header_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('games_header_image_id_fkey', 'games', 'uploads', ['header_image_id'], ['id'])
    # ### end Alembic commands ###
